### ISSUE TITLE
I am having difficulties disabling this extension?

### ISSUE THREAD

**Issue by ibavido** [laurent35240/magento-sass#9]
How can I properly disable this extension from my store?

Note: MYdownloader is not working.

Thank you

**Comment by laurent35240** [comment]
To manually disable this extension, you need to remove the following files and folders:
app/code/community/Laurent/Sass
app/etc/modules/Laurent_Sass.xml
app/locale/en_US/Laurent_Sass.csv
app/locale/fr_FR/Laurent_Sass.csv
lib/phpsass
